apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: ToolServer
metadata:
  name: cloudland-talks-mcp
spec:
  protocol: mcp
  transportType: http
  image: ghcr.io/agentic-layer/workshop/cloudland-talks-mcp:sha-8a18ae0
  port: 8000
  replicas: 1
  env:
    - name: LOGLEVEL
      value: DEBUG
